CXX = g++
CFLAGS = -std=c++0x -O3 -g3 -c -fmessage-length=0
RM = rm

# ****************************************************


main: DividerBMA.o
	$(CXX) -o main DividerBMA.o
# ****************************************************

DividerBMA.o : DividerBMA.cpp
	$(CXX) $(CFLAGS) -c DividerBMA.cpp



